# Java Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.43-beta

## Mod Properties
mod_id=matterfactory
mod_name=Matter Factory
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.iso2t.matterfactory

## Integrations
jei_version=30.1.0.12
