license="${mod_license}"
issueTrackerURL="https://github.com/iso2t/Matter-Factory/issues"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/iso2t/Matter-Factory"
#logoFile="examplemod.png" #optiona
#credits="" #optional
authors="iso2t"
description='''
Matter gathering, duplication, and processing.
'''

#[[mixins]]
#config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
